artifactory:
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "6"
  javaOpts:
    xms: "4g"
    xmx: "6g"
  postgresql:
    enabled: false
  database:
    type: postgresql
    driver: org.postgresql.Driver
    ## If you set the url, leave host and port empty
    url: jdbc:postgresql://
    ## If you would like this chart to create the secret containing the db
    ## password, use these values
    user: yalla-user
    password: howdy-yalla