apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: artifactory
spec:
  analyzers:
    - nodeResources:
        checkName: Cluster Memory
        outcomes:
          - fail:
              when: "sum(memoryAllocatable) < 4Gi"
              message: A medium install requires 4Gi allocatable cluster memory
              uri: https://github.com/jfrog/charts/blob/master/stable/artifactory/values-medium.yaml
          - warn:
              when: "sum(memoryAllocatable) < 8Gi"
              message: A medium install recommends 8Gi allocatable cluster memory
              uri: https://github.com/jfrog/charts/blob/master/stable/artifactory/values-medium.yaml
          - pass:
              message: Cluster has at least 8Gi of allocatable memory
    - nodeResources:
        checkName: Cluster CPUs
        outcomes:
          - fail:
              when: "sum(cpuAllocatable) < 2"
              message: A medium install requires 2 allocatable cluster CPUs
              uri: https://github.com/jfrog/charts/blob/master/stable/artifactory/values-medium.yaml
          - warn:
              when: "sum(cpuAllocatable) < 6"
              message: A medium install recommends 6 allocatable cluster CPUs
              uri: https://github.com/jfrog/charts/blob/master/stable/artifactory/values-medium.yaml
          - pass:
              message: Cluster has 6 or more allocatable CPU cores
