apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: artifactory
spec:
  analyzers:
    - nodeResources:
        checkName: Cluster Memory
        outcomes:
          - fail:
              when: "sum(memoryAllocatable) < 6Gi"
              message: A large install requires 6Gi allocatable cluster memory
              uri: https://github.com/jfrog/charts/blob/master/stable/artifactory/values-large.yaml
          - warn:
              when: "sum(memoryAllocatable) < 10Gi"
              message: A large install recommends 10Gi allocatable cluster memory
              uri: https://github.com/jfrog/charts/blob/master/stable/artifactory/values-large.yaml
          - pass:
              message: Cluster has at least 10Gi of allocatable memory
    - nodeResources:
        checkName: Cluster CPUs
        outcomes:
          - fail:
              when: "sum(cpuAllocatable) < 4"
              message: A large install requires 4 allocatable cluster CPUs
              uri: https://github.com/jfrog/charts/blob/master/stable/artifactory/values-large.yaml
          - warn:
              when: "sum(cpuAllocatable) < 8"
              message: A large install recommends 8 allocatable cluster CPUs
              uri: https://github.com/jfrog/charts/blob/master/stable/artifactory/values-large.yaml
          - pass:
              message: Cluster has 8 or more allocatable CPU cores
