apiVersion: troubleshoot.replicated.com/v1beta1
kind: SupportBundle
metadata:
  name: artifactory
spec:
  collectors:
    - logs:
        selector:
          - app=artifactory
        namespace: artifactory-oss
        name: artifactory-oss
  analyzers:
    - nodeResources:
        checkName: Cluster Memory
        outcomes:
          - warn:
              when: "sum(memoryAllocatable) < 1Gi"
              message: Allocatable memory in cluster is less than 1Gi
              uri: https://github.com/jfrog/charts/blob/master/stable/artifactory/values-medium.yaml
          - pass:
              message: Cluster has at least 1Gi of allocatable memory
    - nodeResources:
        checkName: Cluster CPUs
        outcomes:
          - warn:
              when: "sum(cpuAllocatable) < 1000m"
              message: Allocatable cpus in cluster is less than 1000m
              uri: https://github.com/jfrog/charts/blob/master/stable/artifactory/values-medium.yaml
          - pass:
              message: Cluster has at least 1000m of allocatable cpu
    - statefulsetStatus:
        checkName: Artifactory Status
        name: artifactory-oss
        namespace: artifactory-oss
        outcomes:
          - fail:
              when: "< 1"
              message: The artifactory statefulset does not have any ready replicas.
          - pass:
              message: The artifactory statefulset is ready.
    - deploymentStatus:
        checkName: Nginx Status
        name: artifactory-oss-artifactory-nginx
        namespace: artifactory-oss
        outcomes:
          - fail:
              when: "< 1"
              message: The artifactory-nginx deployment does not have any ready replicas.
          - pass:
              message: The artifactory-nginx deployment is ready.
    - textAnalyze:
        checkName: Database Connection
        fileName: artifactory-oss/artifactory-oss-0/artifactory.log
        regex: 'Could not initialize database: The connection attempt failed.'
        outcomes:
          - pass:
              when: "false"
              message: "Database connection successful"
          - fail:
              when: "true"
              message: "Artifactory pod unable to connect to database"
              uri: https://github.com/dexhorthy/jfrog-charts/tree/add-troubleshoot/stable/artifactory-oss#ingress-and-tls
    - textAnalyze:
        checkName: Database Authentication
        fileName: artifactory-oss/artifactory-oss-0/artifactory.log
        regex: 'FATAL: password authentication failed for user'
        outcomes:
          - pass:
              when: "false"
              message: "Database credentials okay"
          - fail:
              when: "true"
              message: "Problem with artifactory database credentials"
              uri: https://github.com/dexhorthy/jfrog-charts/tree/add-troubleshoot/stable/artifactory-oss#ingress-and-tls
